/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fygrusrtiwiyiqvpznty"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Z3J1c3J0aXdpeWlxdnB6bnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMjIxMDAsImV4cCI6MjA4OTg5ODEwMH0.-qme2A5IZxpBYt_HkGro-6C8zW4t2PjtwUBeKG5g8tI"