// Paiements des parents pour les sessions de tutorat

export const mockParentPayments = [
  {
    id: 'payment-1',
    parentName: 'Marie Lapointe',
    studentName: 'Sophie Lapointe',
    studentId: 'student-2',
    email: 'marie.lapointe@gmail.com',
    phone: '514-555-1234',
    sessionDate: '2026-02-20',
    sessionTime: '14:00',
    tutorName: 'Marie Dubois',
    tutorId: 'tutor-1',
    subject: 'Mathématiques',
    duration: 1.5,
    hourlyRate: 55,
    amount: 82.50,
    paymentDate: '2026-02-20T16:30:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-001-2026',
  },
  {
    id: 'payment-2',
    parentName: 'Marie Lapointe',
    studentName: 'Sophie Lapointe',
    studentId: 'student-2',
    email: 'marie.lapointe@gmail.com',
    phone: '514-555-1234',
    sessionDate: '2026-02-25',
    sessionTime: '14:00',
    tutorName: 'Marie Dubois',
    tutorId: 'tutor-1',
    subject: 'Mathématiques',
    duration: 1.5,
    hourlyRate: 55,
    amount: 82.50,
    paymentDate: '2026-02-25T15:45:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-002-2026',
  },
  {
    id: 'payment-3',
    parentName: 'Jean Tremblay',
    studentName: 'Lucas Gagnon',
    studentId: 'student-3',
    email: 'j.tremblay@hotmail.com',
    phone: '438-555-7890',
    sessionDate: '2026-02-28',
    sessionTime: '16:00',
    tutorName: 'Sophie Martin',
    tutorId: 'tutor-3',
    subject: 'Anglais',
    duration: 1,
    hourlyRate: 50,
    amount: 50.00,
    paymentDate: '2026-02-28T18:00:00',
    paymentMethod: 'Carte de crédit',
    status: 'completed',
    invoiceNumber: 'REC-003-2026',
  },
  {
    id: 'payment-4',
    parentName: 'Parent Test',
    studentName: 'Élève Test',
    studentId: 'student-1',
    email: 'parent@example.com',
    phone: '514-555-0000',
    sessionDate: '2026-03-05',
    sessionTime: '14:00',
    tutorName: 'Marie Dubois',
    tutorId: 'tutor-1',
    subject: 'Mathématiques',
    duration: 1.5,
    hourlyRate: 55,
    amount: 82.50,
    paymentDate: '2026-03-05T16:00:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-004-2026',
  },
  {
    id: 'payment-5',
    parentName: 'Sophie Gagnon',
    studentName: 'Emma Gagnon',
    studentId: 'student-4',
    email: 'sophie.gagnon@gmail.com',
    phone: '450-555-3456',
    sessionDate: '2026-03-01',
    sessionTime: '17:00',
    tutorName: 'Jean Tremblay',
    tutorId: 'tutor-2',
    subject: 'Français',
    duration: 1,
    hourlyRate: 50,
    amount: 50.00,
    paymentDate: '2026-03-01T19:30:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-005-2026',
  },
  {
    id: 'payment-6',
    parentName: 'Isabelle Roy',
    studentName: 'Thomas Roy',
    studentId: 'student-5',
    email: 'isabelle.roy@outlook.com',
    phone: '514-555-6789',
    sessionDate: '2026-02-26',
    sessionTime: '15:00',
    tutorName: 'Sophie Martin',
    tutorId: 'tutor-3',
    subject: 'Anglais',
    duration: 2,
    hourlyRate: 50,
    amount: 100.00,
    paymentDate: '2026-02-26T17:30:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-006-2026',
  },
  {
    id: 'payment-7',
    parentName: 'Alexandre Dubois',
    studentName: 'Alexandre Dubois',
    studentId: 'student-6',
    email: 'alex.dubois@gmail.com',
    phone: '438-555-2345',
    sessionDate: '2026-03-02',
    sessionTime: '19:00',
    tutorName: 'Marie Dubois',
    tutorId: 'tutor-1',
    subject: 'Chimie organique',
    duration: 1.5,
    hourlyRate: 60,
    amount: 90.00,
    paymentDate: '2026-03-02T21:00:00',
    paymentMethod: 'Carte de crédit',
    status: 'completed',
    invoiceNumber: 'REC-007-2026',
  },
  {
    id: 'payment-8',
    parentName: 'Marc Bouchard',
    studentName: 'Gabriel Bouchard',
    studentId: 'student-7',
    email: 'marc.bouchard@gmail.com',
    phone: '514-555-4567',
    sessionDate: '2026-02-24',
    sessionTime: '17:00',
    tutorName: 'Jean Tremblay',
    tutorId: 'tutor-2',
    subject: 'Mathématiques',
    duration: 2,
    hourlyRate: 50,
    amount: 100.00,
    paymentDate: '2026-02-24T19:30:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-008-2026',
  },
  {
    id: 'payment-9',
    parentName: 'Patrick Côté',
    studentName: 'Olivia Côté',
    studentId: 'student-8',
    email: 'p.cote@gmail.com',
    phone: '514-555-7777',
    sessionDate: '2026-03-01',
    sessionTime: '10:00',
    tutorName: 'Marie Dubois',
    tutorId: 'tutor-1',
    subject: 'Physique',
    duration: 2,
    hourlyRate: 55,
    amount: 110.00,
    paymentDate: '2026-03-01T12:30:00',
    paymentMethod: 'Virement Interac',
    status: 'completed',
    invoiceNumber: 'REC-009-2026',
  },
  {
    id: 'payment-10',
    parentName: 'Parent Test',
    studentName: 'Élève Test',
    studentId: 'student-1',
    email: 'parent@example.com',
    phone: '514-555-0000',
    sessionDate: '2026-03-08',
    sessionTime: '10:00',
    tutorName: 'Jean Tremblay',
    tutorId: 'tutor-2',
    subject: 'Français',
    duration: 2,
    hourlyRate: 50,
    amount: 100.00,
    paymentDate: null,
    paymentMethod: null,
    status: 'pending',
    invoiceNumber: 'REC-010-2026',
  },
];

// Fonction pour initialiser les paiements dans localStorage
export const initializeMockPayments = () => {
  const existing = localStorage.getItem('parentPayments');
  if (!existing) {
    localStorage.setItem('parentPayments', JSON.stringify(mockParentPayments));
    console.log('Paiements parents mock initialisés');
  }
};
